name: Build and Deploy Code

on:
    push:
        branches:
            - main
            - CI/CD
    pull_request:
        branches:
            - main

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - name: pulling git repo
              uses: actions/checkout@v6
            - name: say hi to aldrich
              run: echo "Hi Aldrich!"
            
            